import {DriveWorkspace} from './drive.js';
import {uid,day,tomorrow,emptyState,demoState,validateState,suggestions,setFocus,applyAgentUpdate} from './model.js';
const cfg=window.FIELDNOTES_CONFIG||{};
const app=document.querySelector('#app'),dialog=document.querySelector('#editor');
let state=emptyState(),mode='locked',view='today',projectId='',filter='Active',paperFilter='',client=null,user=null,revision=0,hasRow=false,saving=false,saveFailed=false,saveQueue=Promise.resolve(),sessionEpoch=0;
let events=[],zotero=[],googleToken='',googleExpiry=0,zoteroKey='',zoteroUser='',googleConnected=false,zoteroConnected=false,authFactor='',authStep='password',authError='',authBusy=false,authQR='',authSecret='',formHandler=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
const link=(url,label)=>`<a href="${esc(safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;
const btn=(label,action,id='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;
const projectName=id=>state.projects.find(p=>p.id===id)?.title||'General';
const dateLabel=s=>s?new Date(s.length===10?s+'T12:00:00':s).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Not set';
const pill=(text,cls='')=>`<span class="pill ${cls}">${esc(text)}</span>`;
const panel=(title,body,action='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div>${body}</section>`;
const empty=text=>`<div class="empty">${text}</div>`;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',5000);}
function field(name,label,value='',type='text',required=false){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='url'?'placeholder="https://…"':''}></label>`;}
function area(name,label,value='',cls=''){return `<label>${esc(label)}<textarea name="${name}" class="${cls}">${esc(value)}</textarea></label>`;}
function select(name,label,options,value=''){return `<label>${esc(label)}<select name="${name}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;}
const projectSelect=(value='')=>select('project','Linked project',[['','General / no project'],...state.projects.map(p=>[p.id,p.title])],value);
function openForm(title,html,handler,submit='Save'){
  document.querySelector('#editor-content').innerHTML=`<h2>${esc(title)}</h2><div class="fields">${html}</div><p id="form-error" class="error" role="alert"></p>`;
  const submitButton=document.querySelector('#edit-form button[type=submit]');submitButton.textContent=submit;submitButton.disabled=false;
  formHandler=handler;dialog.showModal();
}
document.querySelector('#edit-form').addEventListener('submit',async e=>{
  e.preventDefault();const b=e.submitter;b.disabled=true;
  try{await formHandler(Object.fromEntries(new FormData(e.target)));dialog.close();render();}catch(err){document.querySelector('#form-error').textContent=err.message;}finally{b.disabled=false;}
});
dialog.addEventListener('close',()=>{document.querySelector('#editor-content').replaceChildren();formHandler=null;});
function snapshot(){return JSON.parse(JSON.stringify(state));}
async function commit(){
  if(mode==='demo'){render();return;}
  if(mode!=='private'||!driveConnected)throw new Error('Sign in and connect Drive first.');
  if(saveFailed)throw new Error('Resolve the previous save error in Settings before making more changes.');
  const copy=snapshot(),epoch=sessionEpoch;saving=true;
  saveQueue=saveQueue.then(async()=>{
    if(epoch!==sessionEpoch)return;
    if(saveFailed)throw new Error('Earlier changes are not saved. Use Retry save in Settings.');
    await drive.save(copy);
  }).catch(err=>{saveFailed=true;toast('Not saved: '+err.message);throw err;}).finally(()=>{saving=false;});
  try{await saveQueue;}finally{saveQueue=saveQueue.catch(()=>{});render();}
}
async function change(fn){if(mode==='private'&&!driveConnected)throw new Error('Connect your Drive storage account in Settings before adding data.');if(saveFailed)throw new Error('Resolve the save error in Settings first.');if(saving)throw new Error('Please wait for the current save to finish.');fn();await commit();}
function taskRows(tasks){return tasks.length?tasks.map(t=>`<div class="task-row ${t.done?'completed':''}">${btn(t.done?'✓':'','toggle-task',t.id,'check '+(t.done?'done':''))}<div class="task-body"><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span>${esc(projectName(t.project))}</span>${t.due?pill('Due '+dateLabel(t.due),t.due<day()&&!t.done?'red':''):''}${t.date&&t.date!==day()?`<span>Planned ${dateLabel(t.date)}</span>`:''}</div></div><div class="task-actions">${!t.done?btn(t.focus?'Focusing':'Focus','focus',t.id,t.focus?'selected':'quiet'):''}${btn('Edit','task',t.id,'quiet')}</div></div>`).join(''):empty('A little space to think. Add your next concrete action.');}
function projectCard(p){const open=state.tasks.filter(t=>t.project===p.id&&!t.done).length;return `<article class="project-card"><div class="row spread">${pill(p.status,p.status==='Exploring'?'lime':'')}${pill('Research')}</div><h3>${esc(p.title)}</h3><p>${esc(p.question||'Add a working research question.')}</p><div class="project-footer"><span>${open} open action${open===1?'':'s'}</span>${btn('Open workspace ↗','open-project',p.id,'text-link')}</div></article>`;}
function todayView(){
  const focus=state.tasks.find(t=>t.focus&&!t.done),todayTasks=state.tasks.filter(t=>t.date===day()||t.priority&&!t.done),active=state.projects.filter(p=>!['Someday','Paused','Completed'].includes(p.status)).slice(0,2);
  const focusCard=`<section class="focus-card"><div><div class="eyebrow">One thing at a time</div><h2>${esc(focus?.title||'Choose a small next step.')}</h2><p>${focus?esc(projectName(focus.project)):'Your priorities. Your pace.'}</p></div><div class="focus-bottom">${focus?btn('✓ Mark complete','toggle-task',focus.id):btn('+ Choose an action','task')}<span class="small">${focus?'Current focus':'Make room for deep work'}</span></div></section>`;
  const planned=panel(`Today’s priorities <span class="count">${todayTasks.filter(t=>t.done).length}/${todayTasks.length}</span>`,taskRows(todayTasks)+btn('+ Add a priority','task','','inline-add'),btn('All tasks ↗','nav','tasks','text-link'));
  const suggestionBody=suggestions(state).map(({task,reason})=>`<div class="mini-project"><div class="row spread">${pill(reason,'amber')}${btn('Add to today','prioritize',task.id,'text-link')}</div><h3>${esc(task.title)}</h3></div>`).join('')||empty('Suggestions will appear as you add tasks and deadlines.');
  const agenda=events.filter(e=>(e.start.date||e.start.dateTime?.slice(0,10))===day()).map(eventHTML).join('')||empty(googleConnected?'No events today.':'Connect Google Calendar to see today’s commitments.');
  const due=state.venues.filter(v=>v.deadline&&v.status==='Targeting').sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,3).map(v=>`<div class="event"><h3>${esc(v.name)} · ${esc(v.track)}</h3><p>${esc(dateLabel(v.deadline))} · ${esc(v.zone)}</p></div>`).join('')||empty('No submission commitment yet. Explore first, then choose your target.');
  return `<div class="layout"><div class="stack">${focusCard}${planned}<section><div class="panel-head"><h2>Active explorations</h2>${btn('View all ↗','nav','ideas','text-link')}</div><div class="project-grid">${active.map(projectCard).join('')||empty('Add an idea to begin.')}</div></section>${panel('A note before you move on','<p class="muted small">Capture what you did, learned, and want to try next.</p>'+btn('+ Quick work log','log','','primary'))}</div><div class="stack">${panel('On your calendar',agenda,btn(googleConnected?'Refresh':'Connect','google','','text-link'))}${panel('Worth considering',suggestionBody+'<p class="footer-note">Suggestions stay here until you choose them.</p>')}${panel('On the horizon',due,btn('Venues ↗','nav','venues','text-link'))}${panel('Prelim preparation',`<p class="small muted">${state.prelim.date?'Planned for '+dateLabel(state.prelim.date):'Date not set · build the argument as you explore'}</p><p class="small">${esc(state.prelim.topic||'Connect your questions, literature, and findings.')}</p>${btn('Open prelim workspace ↗','nav','prelim','text-link')}`)}</div></div>`;
}
function ideasView(){const projects=state.projects.filter(p=>filter==='All'||(filter==='Active'?!['Someday','Paused','Completed'].includes(p.status):['Someday','Paused'].includes(p.status)));return `<div class="tabs">${['Active','Backlog','All'].map(f=>btn(f,'filter',f,filter===f?'active':'')).join('')}</div><div class="project-grid">${projects.map(projectCard).join('')||empty('No ideas here yet.')}</div>`;}
function projectView(){const p=state.projects.find(x=>x.id===projectId);if(!p)return empty('Project not found.');return `<div class="row spread" style=""><div class="row">${pill(p.status,'lime')}${btn('← All ideas','nav','ideas','text-link')}</div>${btn('Edit idea','project',p.id)}</div><div class="layout subheading"><div class="stack">${panel('Working question',`<p class="note">${esc(p.question||'Not captured yet.')}</p>`)}${panel('Graphics / CV direction',`<div class="note">${esc(p.method||'Capture the method, assumptions, and technical uncertainties.')}</div>`)}${panel('MR / interaction direction',`<div class="note">${esc(p.interaction||'Capture the scenario, controls, and evaluation questions.')}</div>`)}${panel('Next actions',taskRows(state.tasks.filter(t=>t.project===p.id)),btn('+ Task','task-for',p.id,'text-link'))}${panel('Related reading',papersHTML(state.papers.filter(x=>x.project===p.id)),btn('+ Paper','paper-for',p.id,'text-link'))}</div><div class="stack">${panel('Next exploration',`<p class="note">${esc(p.next||'Choose one uncertainty to investigate.')}</p>${btn('Turn into a task','next-task',p.id,'text-link')}`)}${panel('Starting references',`<div class="note">${esc(p.references||'Link papers from the reading library below.')}</div>`)}${panel('Research trail',state.logs.filter(l=>l.project===p.id).slice().reverse().map(l=>`<div class="mini-project"><span class="muted small">${dateLabel(l.date)}</span><p class="note">${esc(l.learned||l.did)}</p></div>`).join('')||empty('Linked work logs appear here.'))}</div></div>`;}
function tasksView(){return `<div class="tabs">${['Open','Today','Tomorrow','Completed','All'].map(f=>btn(f,'filter',f,filter===f?'active':'')).join('')}</div>${panel('Your next actions',taskRows(state.tasks.filter(t=>filter==='All'||filter==='Completed'?filter==='All'||t.done:filter==='Today'?t.date===day():filter==='Tomorrow'?t.date===tomorrow():!t.done)))}`;}
function papersHTML(papers){return papers.length?papers.map(p=>`<article class="paper"><div class="paper-icon">▤</div><div class="paper-main"><h3>${link(p.url,p.title)}</h3><div class="row">${pill(p.status||'To read')}${pill(p.lens||'Background','blue')}<span class="muted small">${esc(projectName(p.project))}</span></div><p class="note">${esc(p.note||'Add evidence, limitations, and relevance as you read.')}</p></div>${btn('Edit','paper',p.id,'quiet')}</article>`).join(''):empty('Save a paper or connect Zotero to start your reading queue.');}
function papersView(){return `<div class="callout">Keep demonstrated capabilities separate from potential gaps. “Recent” is not automatically “best”; record the benchmark and operating conditions.</div><div class="row spread"><label class="search">Search your reading queue<input id="paper-search" type="search" value="${esc(paperFilter)}" placeholder="Title, notes, or research lens"></label>${btn(zoteroConnected?'Browse Zotero':'Connect Zotero','zotero','','primary')}</div><section class="panel subheading" id="paper-results">${papersHTML(state.papers.filter(p=>`${p.title} ${p.note} ${p.lens}`.toLowerCase().includes(paperFilter.toLowerCase())))}</section>${zoteroConnected?panel('Your Zotero library',`<div class="row">${btn('Search / refresh','zotero','','text-link')}<span class="muted small">Up to 100 results · read-only connection</span></div>`+zotero.map(p=>`<div class="paper"><div class="paper-main"><h3>${esc(p.data.title||p.data.itemType)}</h3><p>${esc(p.data.date||'')} · ${esc(p.data.creators?.map(c=>c.lastName||c.name).filter(Boolean).join(', ')||'')}</p></div>${btn('Add to reading','add-zotero',p.key,'text-link')}</div>`).join('')):''}`;}
function prelimView(){return `<div class="callout">Your thesis direction can evolve. Link daily findings to the survey and distinguish candidate gaps from verified ones.</div><div class="layout"><div class="stack">${[['topic','Working thesis topic'],['questions','Research questions'],['survey','Literature synthesis'],['gaps','Candidate gaps & supporting evidence'],['progress','Current progress']].map(([k,t])=>panel(t,`<div class="note">${esc(state.prelim[k]||'Not captured yet.')}</div>`,btn('Edit','prelim',k,'text-link'))).join('')}</div><div class="stack">${panel('Exam details',`<p>${state.prelim.date?dateLabel(state.prelim.date):'Date not set'}</p><div class="note">${esc(state.prelim.requirements||'Add your department’s requirements.')}</div>`,btn('Edit','prelim','details','text-link'))}${panel('Evidence in your workspace',`<div class="metric">${state.papers.filter(p=>p.status==='Read').length}</div><p class="muted small">papers marked read</p><div class="metric">${state.logs.length}</div><p class="muted small">work logs to draw from</p>${btn('Review journal ↗','nav','journal','text-link')}`)}</div></div>`;}
function venuesView(){return `<div class="callout">No conference dates are assumed. Add an official source, submission track, deadline timezone, and verification date before relying on a deadline.</div><section class="panel table-wrap"><table><thead><tr><th>VENUE / YEAR</th><th>TRACK & PROJECT</th><th>DEADLINE</th><th>INTENT</th><th>SOURCE</th><th></th></tr></thead><tbody>${state.venues.map(v=>`<tr><td><strong>${esc(v.name)}</strong><br><span class="muted">${esc(v.year||'Year undecided')}</span></td><td>${esc(v.track||'Track undecided')}<br><span class="muted">${esc(v.project?projectName(v.project):'No linked project')}</span></td><td>${v.deadline?esc(dateLabel(v.deadline)+' '+v.deadline.slice(11)):'Not announced / not entered'}<br><span class="muted">${esc(v.zone||'Timezone not set')}</span></td><td>${pill(v.status,v.status==='Preferred'?'lime':'')}</td><td>${v.source?link(v.source,'Official source ↗'):'Source needed'}<br><span class="muted">${v.verified?'Checked '+dateLabel(v.verified):'Unverified'}</span></td><td>${btn('Edit','venue',v.id,'text-link')}</td></tr>`).join('')}</tbody></table>${!state.venues.length?empty('Add venues to watch or target.'):''}</section>`;}
function journalView(){return `<div class="layout"><section class="panel">${state.logs.length?state.logs.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(l=>`<article class="journal-entry"><div class="row spread"><h3>${dateLabel(l.date)}</h3>${btn('Edit','log',l.id,'text-link')}</div>${pill(projectName(l.project))}${[['did','What I did'],['learned','What I learned / blockers'],['next','Next step']].filter(([k])=>l[k]).map(([k,t])=>`<div class="eyebrow">${t}</div><p class="note">${esc(l[k])}</p>`).join('')}${l.next?btn('Plan next step','log-next',l.id,'text-link'):''}</article>`).join(''):empty('A sentence is enough. Record your first work session.')}</section><div class="stack">${panel('Leave yourself a starting point','<p class="small muted">Capture what changed in your thinking, then choose tomorrow’s first action.</p>'+btn('+ Write a quick log','log','','primary'))}${panel('Tomorrow',taskRows(state.tasks.filter(t=>t.date===tomorrow())),btn('+ Plan','tomorrow','','text-link'))}</div></div>`;}
function goalsView(){return panel('Goals that give your work direction',state.goals.map(g=>`<div class="task-row">${btn(g.done?'✓':'','toggle-goal',g.id,'check '+(g.done?'done':''))}<div class="task-body"><h3>${esc(g.title)}</h3><div class="row">${pill(g.horizon)}<span class="muted small">${esc(projectName(g.project))}${g.due?' · '+dateLabel(g.due):''}</span></div></div>${btn('Edit','goal',g.id,'text-link')}</div>`).join('')||empty('Add a short-term milestone or a longer-term ambition.'));}
function eventHTML(e){const d=e.start?.dateTime;return `<div class="event"><h3>${esc(e.summary||'Untitled event')}</h3><p>${d?new Date(d).toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):dateLabel(e.start.date)+' · All day'}</p>${e.htmlLink?link(e.htmlLink,'Open in Google Calendar ↗'):''}</div>`;}
function calendarView(){return `<div class="layout">${panel('Next 14 days',googleConnected?events.map(eventHTML).join('')||empty('No upcoming events.'):empty('Connect your Google Calendar to see your schedule here.'),btn(googleConnected?'Refresh':'Connect','google','','text-link'))}${panel('Planned work',taskRows(state.tasks.filter(t=>!t.done&&t.date&&t.date>=day()).sort((a,b)=>a.date.localeCompare(b.date))))}</div>`;}
function settingsView(){return `<section class="panel settings-card"><h2>Workspace & privacy</h2>${mode==='private'?`<p class="small">Signed in: <strong>${esc(loginEmail)}</strong><br>Drive storage: <strong>${esc(driveEmail ? driveEmail+' · '+(drive.folderName||'Choose folder') : 'Not connected — choose an account below')}</strong></p>`:''}<p class="muted">${mode==='demo'?'Preview changes live only in this tab. Reloading resets the preview.':driveConnected?'Workspace saved in your selected Drive folder. Anyone with access to that folder may also access these saves.':'Sign-in and storage are separate. Choose the Drive account you want to use before adding your research.'}</p><div class="row">${mode==='private'?btn(driveConnected?'Reconnect Google Drive':'Choose Drive storage account','drive-login')+(driveConnected?btn('Version history','drive-history'):''):''}${btn('Export backup','export')}${btn('Import workspace','import')}${mode==='private'?btn('Sign out','logout','','quiet'):btn('Leave preview','logout','','quiet')}</div>${saveFailed?'<p class="error">Changes have not been saved. Export a backup before reloading. A concurrent edit requires a reload and manual merge.</p>'+btn('Retry save','retry'):''}</section><section class="panel settings-card"><h2>Google Calendar</h2><p class="muted">Read your primary calendar. Events and access tokens stay in memory; Fieldnotes does not modify your calendar.</p>${btn(googleConnected?'Refresh calendar':'Connect Google Calendar','google','','primary')}${googleConnected?btn('Disconnect','disconnect-google','','quiet'):''}${!cfg.googleClientId?'<p class="footer-note">Setup needed: Google OAuth client ID and authorized website origin.</p>':''}</section><section class="panel settings-card"><h2>Zotero</h2><p class="muted">Search your synced personal library with a read-only API key. The key stays in memory for this session. Only papers you choose to save enter your workspace.</p>${btn(zoteroConnected?'Browse library':'Connect Zotero','zotero','','primary')}${zoteroConnected?btn('Disconnect','disconnect-zotero','','quiet'):''}</section><section class="panel settings-card"><h2>Publishing checklist</h2><p class="muted small">Configure the Google OAuth client for your GitHub Pages origin. Publish only the public app files. After Google sign-in, import your private starter workspace from Settings.</p>${link('https://github.com/settings/security','GitHub account settings ↗')}</section>`;}
const names={research:'Research',timeline:'Timeline',agent:'Organize with Codex',today:'Today',ideas:'Research ideas',project:'Research workspace',tasks:'Tasks',papers:'Reading library',prelim:'PhD prelim',venues:'Venue watchlist',journal:'Daily journal',goals:'Goals',calendar:'Calendar',settings:'Settings'};
const captions={research:'Your ideas, reading, and thesis in one place.',timeline:'What happened. What comes next.',agent:'Use this Codex conversation. No API key or paid calls.',today:'A clear next step. Space for the bigger picture.',ideas:'Explore the questions before committing to an answer.',tasks:'Small, concrete actions that move your work forward.',papers:'Background, evidence, and the questions still open.',prelim:'Build your argument as your research develops.',venues:'Find the right audience for the contribution.',journal:'A record of the work and the thinking behind it.',goals:'Connect today’s work to what matters over time.',calendar:'Make a plan that fits the time you have.',settings:'Connections, backups, and your private workspace.'};
function render(){
  if(mode==='locked'){renderAuth();return;}
  const nav=[['today','◷','Today'],['research','◇','Research'],['timeline','▥','Timeline'],['agent','✧','Organize with Codex'],['settings','⚙','Settings']];
  const add={today:['+ Add task','task'],ideas:['+ New idea','project'],tasks:['+ Add task','task'],papers:['+ Add paper','paper'],venues:['+ Add venue','venue'],journal:['+ Work log','log'],goals:['+ Add goal','goal']};
  const content={today:simpleToday,research:researchHome,timeline:timelineHome,agent:agentHome,ideas:ideasView,project:projectView,tasks:tasksView,papers:papersView,prelim:prelimView,venues:venuesView,journal:journalView,goals:goalsView,calendar:calendarView,settings:settingsView};
  app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="icon.svg" alt="">Fieldnotes<span class="muted">.</span></div><div class="nav-caption">YOUR WORKSPACE</div><nav>${nav.map(([key,icon,label])=>`<button class="nav-button ${view===key||['project','ideas','papers','prelim','venues','goals'].includes(view)&&key==='research'||['journal','calendar','tasks'].includes(view)&&key==='timeline'?'active':''}" data-action="nav" data-id="${key}" ${view===key?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</button>`).join('')}</nav><div class="nav-bottom"><div class="callout small">Make progress.<br>Keep the questions.</div></div><div class="account"><span class="avatar">${mode==='demo'?'P':'F'}</span><div>${mode==='demo'?'Preview workspace':'Private workspace'}<br><small class="muted">${mode==='demo'?'Session only':'Google Drive'}</small></div></div></aside><main class="workspace"><header class="topbar"><span>Workspace <span class="muted">/ ${names[view]}</span></span><div class="top-actions"><span class="status" role="status">${mode==='demo'?'Preview · not saved':saveFailed?'⚠ Not saved':saving?'Saving…':driveConnected?'Drive · saved':'Drive not connected'}</span>${btn('Capture a note','capture-home','','quiet')}${btn(mode==='demo'?'Exit preview':'Sign out','logout','','quiet')}</div></header>${mode==='demo'?'<div class="banner">Preview mode · explore freely. Changes reset on reload. Connect your private workspace before relying on it.</div>':''}<div class="page"><div class="page-head"><div>${view==='today'?`<div class="eyebrow date">${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</div>`:''}<h1>${esc(view==='today'?'Your day, with a little more focus.':view==='project'?state.projects.find(p=>p.id===projectId)?.title||names[view]:names[view])}</h1><p>${captions[view]||'Explore the method, the interaction, and the evidence.'}</p></div>${view!=='today'&&add[view]?btn(add[view][0],add[view][1],'','primary'):''}</div>${(content[view]||todayView)()}<p class="footer-note">Fieldnotes · A personal research desk</p></div></main></div>`;
  document.querySelectorAll('.check').forEach(b=>{b.setAttribute('aria-label',b.classList.contains('done')?'Mark incomplete':'Mark complete');b.setAttribute('aria-pressed',String(b.classList.contains('done')));});
}
function taskForm(id='',preset={}){const t=state.tasks.find(t=>t.id===id)||{title:'',project:'',date:day(),due:'',priority:false,done:false,focus:false,...preset};openForm(id?'Edit task':'A concrete next action',field('title','What will you do?',t.title,'text',true)+projectSelect(t.project)+`<div class="two-fields">${field('date','Plan for',t.date,'date')}${field('due','Deadline (optional)',t.due,'date')}</div>`+select('priority','Priority',[['false','Normal'],['true','One of my priorities']],String(t.priority))+ (id?btn('Delete task','delete-task',id,'quiet danger'):''),async f=>{await change(()=>{const x={...t,...f,id:id||uid(),priority:f.priority==='true'};if(id)state.tasks[state.tasks.findIndex(t=>t.id===id)]=x;else state.tasks.push(x);});});}
function projectForm(id=''){const p=state.projects.find(x=>x.id===id)||{title:'',status:'Exploring'};openForm(id?'Edit research idea':'New research idea',field('title','Idea / project name',p.title,'text',true)+select('status','Stage',['Exploring','Prototyping','Evaluating','Writing','Submitted','Paused','Someday','Completed'],p.status)+area('question','Working question',p.question)+area('method','Graphics / CV direction',p.method)+area('interaction','MR / interaction direction',p.interaction)+area('next','Next exploration',p.next)+area('references','Starting references / notes',p.references),async f=>change(()=>{if(id)Object.assign(p,f);else state.projects.push({...f,id:uid()});}));}
function paperForm(id='',preset={}){const p=state.papers.find(x=>x.id===id)||{title:'',url:'',status:'To read',lens:'Background',project:'',note:'',...preset};openForm(id?'Paper & evidence':'Add a paper',field('title','Title',p.title,'text',true)+field('url','Paper / project URL',p.url,'url',true)+projectSelect(p.project)+`<div class="two-fields">${select('status','Reading status',['To read','Reading','Read'],p.status)}${select('lens','Research lens',['Background','Graphics / CV','MR / interaction','Evaluation','Recent method'],p.lens)}</div>`+area('note','Evidence, conditions, limitations & relevance',p.note,'tall')+(id?btn('Remove paper','delete-paper',id,'quiet danger'):''),async f=>change(()=>{if(safeURL(f.url)==='#')throw new Error('Use an HTTP or HTTPS link.');if(id)Object.assign(p,f);else state.papers.push({...f,id:uid()});}));}
function logForm(id=''){const l=state.logs.find(x=>x.id===id)||{date:day(),project:'',did:'',learned:'',next:''};openForm(id?'Edit work log':'Capture the work',field('date','Date',l.date,'date',true)+projectSelect(l.project)+area('did','What did you do?',l.did)+(!id?btn('Suggest today’s completed tasks','suggest-log','','text-link'):'')+area('learned','What did you learn? Any blockers?',l.learned)+area('next','Where will you pick up next?',l.next),async f=>{if(!f.did.trim()&&!f.learned.trim()&&!f.next.trim())throw new Error('Write at least one note.');await change(()=>{if(id)Object.assign(l,f);else state.logs.push({...f,id:uid()});});});}
function venueForm(id=''){const v=state.venues.find(x=>x.id===id)||{name:'',year:'',track:'',deadline:'',zone:'',status:'Watching',source:'',verified:'',project:''};openForm(id?'Edit venue target':'Watch a venue',field('name','Conference',v.name,'text',true)+`<div class="two-fields">${field('year','Edition / year',v.year)}${field('track','Submission track',v.track)}</div>`+projectSelect(v.project)+select('status','Intent',['Watching','Preferred','Targeting','Submitted'],v.status)+field('deadline','Deadline in the stated timezone',v.deadline,'datetime-local')+field('zone','Timezone (e.g. America/Los_Angeles or AoE)',v.zone)+field('source','Official source URL',v.source,'url')+field('verified','Last verified',v.verified,'date')+(id?btn('Remove venue','delete-venue',id,'quiet danger'):''),async f=>{if(f.deadline&&(!f.zone||!f.source||!f.verified))throw new Error('A deadline needs its timezone, source, and verification date.');await change(()=>{if(id)Object.assign(v,f);else state.venues.push({...f,id:uid()});});});}
function goalForm(id=''){const g=state.goals.find(x=>x.id===id)||{title:'',horizon:'Short term',project:'',due:'',done:false};openForm(id?'Edit goal':'Add a goal',field('title','What are you working toward?',g.title,'text',true)+select('horizon','Horizon',['Short term','Long term'],g.horizon)+projectSelect(g.project)+field('due','Target date',g.due,'date')+(id?btn('Delete goal','delete-goal',id,'quiet danger'):''),async f=>change(()=>{if(id)Object.assign(g,f);else state.goals.push({...f,done:false,id:uid()});}));}
function prelimForm(key){const labels={topic:'Working thesis topic',questions:'Research questions',survey:'Literature synthesis',gaps:'Candidate gaps & evidence',progress:'Current progress'};openForm(key==='details'?'Exam details':labels[key],key==='details'?field('date','Exam date',state.prelim.date,'date')+area('requirements','Requirements',state.prelim.requirements):area(key,labels[key],state.prelim[key],'tall'),async f=>change(()=>Object.assign(state.prelim,f)));}
function exportData(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download=`fieldnotes-${day()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup exported. It contains your private research notes.');}
function importData(){openForm('Import workspace','<p class="muted small">Import a Fieldnotes JSON backup or your prepared private starter file. This replaces the current workspace; export a backup first if needed.</p><label>Workspace file<input type="file" id="import-file" accept=".json,application/json" required></label>',async()=>{const f=document.querySelector('#import-file').files[0];if(!f||f.size>5e6)throw new Error('Choose a JSON file under 5 MB.');const imported=validateState(JSON.parse(await f.text()));await change(()=>{state=imported;});},'Import & replace');}
function loadScript(src){return new Promise((resolve,reject)=>{const el=document.createElement('script');el.src=src;el.onload=resolve;el.onerror=()=>reject(new Error('Could not load the connection library. Check your network.'));document.head.append(el);});}
const drive=new DriveWorkspace();
let driveReady=false,driveClient=null,driveAccount='',driveEmail='',loginAccount='',loginEmail='',driveConnected=false;
function renderAuth(){app.innerHTML=`<main class="auth"><section class="auth-art"><div class="brand"><img src="icon.svg" alt="">Fieldnotes.</div><div><div class="eyebrow">A personal research desk</div><h1>A little space for your next idea.</h1><p>Your research, notes, and next steps.</p></div><small>Your workspace, stored in your Google Drive.</small></section><section class="auth-main"><div class="auth-box"><h2>Your private workspace</h2><p class="muted">Sign in with your Google account. Then choose the Google Drive account that will store your notes; it can be a different account.</p><p class="error" role="alert">${esc(authError)}</p>${btn(authBusy?'Connecting…':'Continue with Google','google-login','','primary')}${!cfg.googleClientId?'<p class="footer-note">Google sign-in configuration is still needed.</p>':''}${btn('Explore the preview →','demo','','quiet')}<p class="footer-note">Your Google account protects access. Enable Google 2-Step Verification in your account settings; the site does not require a fresh second factor on every visit.</p></div></section></main>`;}
async function prepareDrive(){if(!cfg.googleClientId)return;if(!window.google?.accounts?.oauth2)await loadScript('https://accounts.google.com/gsi/client');driveReady=true;}
async function pickStorageFolder(token){
  if(!cfg.googlePickerApiKey||!cfg.googleAppId)throw new Error('The Google folder picker still needs setup.');
  if(!window.gapi)await loadScript('https://apis.google.com/js/api.js');
  if(!window.google?.picker)await new Promise((resolve,reject)=>window.gapi.load('picker',{callback:resolve,onerror:()=>reject(new Error('Could not load the folder picker.')),timeout:15000,ontimeout:()=>reject(new Error('The folder picker timed out.'))}));
  return new Promise(resolve=>{
    const p=window.google.picker;
    const folders=new p.DocsView(p.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);
    const picker=new p.PickerBuilder().addView(folders).setOAuthToken(token).setDeveloperKey(cfg.googlePickerApiKey).setAppId(cfg.googleAppId).setOrigin(location.origin).setTitle('Select your Fieldnotes storage folder').setCallback(result=>{
      if(result.action===p.Action.PICKED){picker.dispose();resolve(result.docs?.[0]?.id||null);}
      else if(result.action===p.Action.CANCEL){picker.dispose();resolve(null);}
    }).build();picker.setVisible(true);
  });
}
async function googleLogin(){
  if(authBusy)return;
  if(!cfg.googleClientId){toast('Google sign-in setup is not complete yet.');return;}
  if(!driveReady){await prepareDrive();toast('Google is ready. Click Continue with Google again.');return;}
  const epoch=sessionEpoch;authBusy=true;
  const identityClient=window.google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:'openid email',include_granted_scopes:false,callback:async response=>{try{
    if(response.error)throw new Error(response.error_description||response.error);
    const r=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+response.access_token}});if(!r.ok)throw new Error('Could not verify your Google account.');const identity=await r.json();if(epoch!==sessionEpoch)return;
    if(!identity.sub||!identity.email_verified)throw new Error('A verified Google account is required.');
    loginAccount=identity.sub;loginEmail=identity.email;mode='private';state=emptyState();view='settings';sessionEpoch++;authError='';
  }catch(err){authError=err.message;toast(err.message);}finally{authBusy=false;render();}},error_callback:err=>{authBusy=false;authError='Sign-in interrupted: '+err.type;render();}});
  identityClient.requestAccessToken({prompt:'select_account'});
}
async function googleDriveLogin(){
  if(!loginAccount){toast('Sign in first, then choose a Drive storage account.');return;}
  if(authBusy)return;
  if(!cfg.googleClientId){toast('Google sign-in needs its OAuth client ID. Setup instructions are included.');return;}
  if(!driveReady){await prepareDrive();toast('Google is ready. Click Continue with Google again to open sign-in.');return;}
  const epoch=sessionEpoch;authBusy=true;
  driveClient=window.google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:'openid email https://www.googleapis.com/auth/drive.file',include_granted_scopes:false,callback:async response=>{
    if(epoch!==sessionEpoch)return;
    try{if(response.error)throw new Error(response.error_description||response.error);if(!window.google.accounts.oauth2.hasGrantedAllScopes(response,'https://www.googleapis.com/auth/drive.file'))throw new Error('Permission for files you select or create is required to save your workspace.');
      const identityResponse=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+response.access_token}});
      if(!identityResponse.ok)throw new Error('Could not verify your Google account.');
      const identity=await identityResponse.json();
      if(epoch!==sessionEpoch)return;
      if(!identity.sub)throw new Error('Missing Google account identity.');
      if(driveConnected&&driveAccount!==identity.sub)throw new Error('Reconnect the same Google account. Sign out first to switch accounts without mixing workspaces.');
      driveAccount=identity.sub;driveEmail=identity.email;drive.authorize(response.access_token,response.expires_in);
      if(driveConnected){toast('Drive reconnected. Retry any unsaved changes.');return;}
      const folderId=await pickStorageFolder(response.access_token);if(epoch!==sessionEpoch)return;if(!folderId){drive.clear();driveAccount='';driveEmail='';toast('No storage folder selected.');return;}
      await drive.selectFolder(folderId);if(epoch!==sessionEpoch)return;
      const loaded=await drive.load();if(epoch!==sessionEpoch)return;state=loaded.data?validateState(loaded.data):emptyState();driveConnected=true;view='today';authError='';
      if(loaded.versions.length>1&&loaded.versions[0].appProperties?.parent===loaded.versions[1].appProperties?.parent)toast('Overlapping saves found. Version history retains both; review them before continuing.');
      if(!loaded.data)toast('Your private Drive workspace is ready. Import your starter from Settings.');
    }catch(err){authError=err.message;toast(err.message);}finally{authBusy=false;render();}
  },error_callback:err=>{authBusy=false;authError='Google sign-in was interrupted: '+err.type;render();}});
  driveClient.requestAccessToken({prompt:driveConnected?'':'select_account'});
}
async function logout(){if(saving){toast('Please wait for the save to finish.');return;}if(saveFailed)exportData();sessionEpoch++;drive.clear();driveAccount='';driveEmail='';loginAccount='';loginEmail='';driveConnected=false;state=emptyState();mode='locked';view='today';saveFailed=false;saveQueue=Promise.resolve();authBusy=false;authError='';events=[];zotero=[];googleToken='';googleExpiry=0;zoteroKey='';zoteroUser='';googleConnected=false;zoteroConnected=false;if(dialog.open)dialog.close();render();}
async function driveHistory(){const versions=await drive.versions();openForm('Drive version history','<p class="small muted">Choose a saved snapshot to load. Export unsaved work first. Loading does not delete any Drive versions. The newest 100 snapshots are shown.</p>'+select('version','Saved version',versions.map(v=>[v.id,v.createdTime]),versions[0]?.id||''),async f=>{if(!f.version)throw new Error('No saved versions yet.');const recovered=validateState(await drive.read(f.version));if(saveFailed)exportData();state=recovered;drive.head=versions[0]?.id||'';saveFailed=false;render();toast('Snapshot loaded. Save or edit to create a new version.');},'Load snapshot');}
async function connectGoogle(){if(!cfg.googleClientId){toast('Add a Google OAuth client ID to config.js first. Setup instructions are included.');return;}const epoch=sessionEpoch;
  async function fetchEvents(){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+14);let all=[],page='';do{const q=new URLSearchParams({timeMin:start.toISOString(),timeMax:end.toISOString(),singleEvents:'true',orderBy:'startTime',maxResults:'250',...(page?{pageToken:page}:{})});const res=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events?'+q,{headers:{Authorization:'Bearer '+googleToken}});const body=await res.json();if(!res.ok){googleToken='';googleConnected=false;throw new Error(body.error?.message||'Calendar request failed.');}all.push(...(body.items||[]));page=body.nextPageToken||'';}while(page);if(epoch!==sessionEpoch)return;events=all;googleConnected=true;render();toast('Calendar updated.');}
  if(googleToken&&Date.now()<googleExpiry){await fetchEvents();return;}
  if(!window.google?.accounts?.oauth2)await loadScript('https://accounts.google.com/gsi/client');
  const tokenClient=window.google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:'https://www.googleapis.com/auth/calendar.events.readonly',callback:async response=>{if(epoch!==sessionEpoch)return;if(response.error){toast('Google connection: '+response.error);return;}googleToken=response.access_token;googleExpiry=Date.now()+(Number(response.expires_in)-60)*1000;try{await fetchEvents();}catch(err){toast(err.message);}},error_callback:error=>toast('Calendar connection interrupted: '+error.type)});tokenClient.requestAccessToken();
}
function connectZotero(){openForm(zoteroConnected?'Search Zotero':'Connect your Zotero library',`<p class="small muted">Use a key restricted to reading your personal library. Find your user ID and create a key in ${link('https://www.zotero.org/settings/keys','Zotero API settings')}. The key is never written to your workspace.</p>`+field('userId','Zotero numeric user ID',zoteroUser,'text',true)+`<label>Read-only API key<input type="password" name="key" autocomplete="off" required value="${esc(zoteroKey)}"></label>`+field('query','Search title / creator / year',''),async f=>{if(!/^\d+$/.test(f.userId))throw new Error('Use the numeric Zotero user ID.');const q=new URLSearchParams({format:'json',limit:'100',itemType:'-attachment || note',sort:'dateModified',direction:'desc',...(f.query?{q:f.query,qmode:'titleCreatorYear'}:{})});const epoch=sessionEpoch;const r=await fetch(`https://api.zotero.org/users/${f.userId}/items/top?${q}`,{headers:{'Zotero-API-Key':f.key,'Zotero-API-Version':'3'}});if(!r.ok)throw new Error(`Zotero returned ${r.status}. Check the user ID and library read permission.`);const items=await r.json();if(epoch!==sessionEpoch)return;zotero=items;zoteroUser=f.userId;zoteroKey=f.key;zoteroConnected=true;view='papers';},'Connect & search');}
document.addEventListener('input',e=>{if(e.target.id==='paper-search'){paperFilter=e.target.value;document.querySelector('#paper-results').innerHTML=papersHTML(state.papers.filter(p=>`${p.title} ${p.note} ${p.lens}`.toLowerCase().includes(paperFilter.toLowerCase())));}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;try{
  if(a==='close-dialog'){dialog.close();return;}
  if(a==='demo'){mode='demo';sessionEpoch++;state=demoState();if(['127.0.0.1','localhost'].includes(location.hostname)){try{const r=await fetch('/__preview_seed');if(r.ok)state=validateState(await r.json());}catch{}}render();return;}
  if(a==='google-login'){await googleLogin();return;}
  if(a==='drive-login'){await googleDriveLogin();return;}
  if(a==='logout'){captureDraft='';captureImage=null;await logout();return;}
  if(mode==='locked')return;
  if(a==='capture-home'){view='today';render();document.querySelector('#quick-note')?.focus();return;}
  if(a==='drive-history'){await driveHistory();return;}
  if(a==='save-capture'){await saveCapture();return;}
  if(a==='remove-photo'){captureImage=null;render();return;}
  if(a==='agent-import'){agentImport();return;}
  if(a==='handoff'){downloadHandoff();return;}
  if(a==='nav'){view=id;filter=id==='tasks'?'Open':'Active';render();window.scrollTo(0,0);return;}
  if(a==='filter'){filter=id;render();return;}
  if(a==='open-project'){projectId=id;view='project';render();window.scrollTo(0,0);return;}
  if(a==='task'){taskForm(id);return;}if(a==='task-for'){taskForm('',{project:id});return;}if(a==='tomorrow'){taskForm('',{date:tomorrow()});return;}
  if(a==='project'){projectForm(id);return;}if(a==='paper'){paperForm(id);return;}if(a==='paper-for'){paperForm('',{project:id});return;}if(a==='log'){logForm(id);return;}if(a==='venue'){venueForm(id);return;}if(a==='goal'){goalForm(id);return;}if(a==='prelim'){prelimForm(id);return;}
  if(a==='toggle-task'){await change(()=>{const t=state.tasks.find(t=>t.id===id);t.done=!t.done;t.completedOn=t.done?day():'';if(t.done)t.focus=false;});return;}
  if(a==='toggle-goal'){await change(()=>{const g=state.goals.find(g=>g.id===id);g.done=!g.done;});return;}
  if(a==='focus'){await change(()=>setFocus(state,id));toast('Focus set.');return;}
  if(a==='prioritize'){await change(()=>{const t=state.tasks.find(t=>t.id===id);t.date=day();t.priority=true;});return;}
  if(a==='next-task'){const p=state.projects.find(p=>p.id===id);taskForm('',{project:id,title:p.next||''});return;}
  if(a==='suggest-log'){const done=state.tasks.filter(t=>t.done&&t.completedOn===day()).map(t=>'• '+t.title).join('\n');document.querySelector('[name=did]').value=done||'No tasks completed today yet.';return;}
  if(a==='log-next'){const l=state.logs.find(l=>l.id===id);taskForm('',{title:l.next,project:l.project,date:tomorrow()});return;}
  if(a.startsWith('delete-')){const key={task:'tasks',paper:'papers',venue:'venues',goal:'goals'}[a.slice(7)];if(key){await change(()=>{state[key]=state[key].filter(x=>x.id!==id);});dialog.close();}return;}
  if(a==='export'){exportData();return;}if(a==='import'){importData();return;}if(a==='retry'){saveFailed=false;await commit();return;}
  if(a==='google'){await connectGoogle();return;}if(a==='zotero'){connectZotero();return;}
  if(a==='disconnect-google'){googleToken='';googleExpiry=0;googleConnected=false;events=[];render();return;}
  if(a==='disconnect-zotero'){zoteroKey='';zoteroUser='';zotero=[];zoteroConnected=false;render();return;}
  if(a==='add-zotero'){const item=zotero.find(p=>p.key===id);paperForm('',{title:item.data.title,url:item.data.url||item.links?.alternate?.href||`https://www.zotero.org/users/${zoteroUser}/items/${id}`,note:'Imported from Zotero. Evidence and limitations not yet reviewed.'});return;}
}catch(err){toast(err.message);}});
let captureDraft='',captureImage=null;
function captureBox(){return `<section class="capture-box"><label for="quick-note">What’s on your mind?</label><textarea id="quick-note" placeholder="Read a paper today. Tomorrow, follow up on the experiment idea…">${esc(captureDraft)}</textarea>${captureImage?`<div class="capture-photo"><img src="${captureImage.data}" alt="Attached note"><span>${esc(captureImage.name)}</span>${btn('Remove','remove-photo','','quiet')}</div>`:''}<div class="row spread"><div class="row"><label class="photo-button">＋ Photo<input id="capture-photo" type="file" accept="image/png,image/jpeg,image/webp"></label><span class="small muted">Type or use your device’s dictation</span></div>${btn('Save note','save-capture','','primary')}</div><p class="capture-hint">No forms. Save the thought now; organize it with Codex when you’re ready.</p></section>`;}
function simpleToday(){
  const focus=state.tasks.find(t=>t.focus&&!t.done),tasks=state.tasks.filter(t=>!t.done&&(t.date===day()||t.priority)).slice(0,3);
  return captureBox()+`<div class="simple-day"><section class="focus-card"><div><div class="eyebrow">Right now</div><h2>${esc(focus?.title||'Choose your next small step.')}</h2><p>${focus?esc(projectName(focus.project)):'Your priorities stay yours.'}</p></div><div class="focus-bottom">${focus?btn('✓ Done','toggle-task',focus.id):btn('Choose from tasks','nav','tasks')}</div></section>${panel('Next up',taskRows(tasks),btn('All tasks','nav','tasks','text-link'))}</div><div class="simple-day">${panel('Recent thoughts',recentCaptures(3),btn('Timeline ↗','nav','timeline','text-link'))}${panel('Coming up',`<p class="small muted">${state.prelim.date?'Prelim · '+dateLabel(state.prelim.date):'Prelim date not set'}</p>`+events.slice(0,2).map(eventHTML).join('')+btn('Calendar','nav','calendar','text-link')+' · '+btn('Conference deadlines','nav','venues','text-link'))}</div>`;
}
function recentCaptures(limit=100){const notes=(state.captures||[]).slice().reverse().slice(0,limit);return notes.length?notes.map(n=>`<article class="capture-entry"><span class="muted small">${dateLabel(n.createdAt)}</span><p class="note">${esc(n.text)}</p>${n.image&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(n.image.data)?`<img class="note-photo" src="${n.image.data}" alt="${esc(n.image.name)}">`:''}</article>`).join(''):empty('Ideas, observations, and reminders can all start as a quick note.');}
function researchHome(){return `<div class="research-links">${[['papers','Reading library','Papers, evidence & Zotero'],['prelim','PhD prelim','Your argument as it develops'],['venues','Venues','SIGGRAPH and your watchlist']].map(([id,title,desc])=>`<button data-action="nav" data-id="${id}"><strong>${title} ↗</strong><span>${desc}</span></button>`).join('')}</div><div class="panel-head"><h2>Active ideas</h2>${btn('All ideas & backlog','nav','ideas','text-link')}</div><div class="project-grid">${state.projects.filter(p=>!['Someday','Paused','Completed'].includes(p.status)).map(projectCard).join('')||empty('Capture your first research idea on Today.')}</div><div class="research-bottom">${btn('Goals','nav','goals','text-link')}<span>Keep the big picture close.</span></div>`;}
function timelineHome(){return `<div class="tabs">${btn('Work logs','nav','journal')}${btn('Calendar','nav','calendar')}${btn('Tasks & tomorrow','nav','tasks')}</div><div class="layout"><div class="stack">${panel('Captured thoughts',recentCaptures())}${panel('Work history',state.logs.slice().reverse().map(l=>`<article class="capture-entry"><span class="muted small">${dateLabel(l.date)} · ${esc(projectName(l.project))}</span><p class="note">${esc(l.did)}</p><p class="note muted">${esc(l.learned)}</p>${l.next?`<p class="small">Next: ${esc(l.next)}</p>`:''}</article>`).join('')||empty('Work logs appear here after you organize your notes.'))}</div><div>${panel('Tomorrow',taskRows(state.tasks.filter(t=>t.date===tomorrow()&&!t.done)))}</div></div>`;}
function agentHome(){return `<section class="panel agent-intro"><span class="eyebrow">Your existing subscription</span><h2>Tell Codex. Let it do the organizing.</h2><p>Speak, write, or attach photos in this Codex conversation. Ask it to turn your thoughts into tasks, research notes, reading, or goals.</p><blockquote>“I worked on lighting today. Add a note about the occlusion issue, and remind me to compare depth methods tomorrow.”</blockquote><div class="agent-steps"><div><strong>1. Bring the context</strong><p>Download your workspace and attach it here if Codex needs your latest notes. Attach original photos here for image analysis.</p>${btn('Download context','handoff','','primary')}</div><div><strong>2. Ask Codex to organize it</strong><p>Codex returns a small update file. It uses your subscription allowance, with no API calls from this site.</p></div><div><strong>3. Review the additions</strong><p>Import the update, review what will be added, then apply it. Existing work is preserved.</p>${btn('Review an update','agent-import','','primary')}</div></div><p class="footer-note">This is a file handoff, not a live agent connection. Photos saved on the site are attachments; they are not automatically interpreted. Voice input happens in Codex or through your device’s dictation.</p></section>`;}
async function saveCapture(){if(!captureDraft.trim()&&!captureImage){toast('Write a thought or attach a photo first.');return;}if(saving||saveFailed)throw new Error('Resolve the pending save first.');const record={id:uid(),createdAt:new Date().toISOString(),text:captureDraft.trim(),...(captureImage?{image:captureImage}:{})};if(new Blob([JSON.stringify(state),JSON.stringify(record)]).size>4.5e6)throw new Error('This workspace is getting large. Export your notes and use links for additional photos.');await change(()=>{state.captures=[...(state.captures||[]),record];});captureDraft='';captureImage=null;render();toast(mode==='demo'?'Captured in this preview. Export before reloading to keep it.':'Note saved.');}
function downloadHandoff(){const payload={kind:'fieldnotes-context',version:1,instructions:'Read AGENT-WORKFLOW.md for the update format. Return an additive fieldnotes-update JSON file for review. Do not invent deadlines, completed work, or paper findings. The workspace is private. For photo understanding ask for the original images as attachments rather than attempting to interpret base64 strings.',workspace:state};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fieldnotes-context-${day()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function agentImport(){let proposed=null;openForm('Review a Codex update','<p class="small muted">Choose the update file Codex prepared. Nothing is changed until you review and apply it.</p><label>Update file<input id="agent-file" type="file" accept=".json,application/json" required></label><div id="agent-review"></div>',async()=>{if(!proposed)throw new Error('Choose a valid update file first.');const next=applyAgentUpdate(state,proposed);await change(()=>{state=next;});toast('Update applied. Your existing records were preserved.');},'Apply additions');document.querySelector('#agent-file').addEventListener('change',async e=>{proposed=null;const el=document.querySelector('#agent-review');try{const f=e.target.files[0];if(!f||f.size>1e6)throw new Error('Choose an update under 1 MB.');const candidate=JSON.parse(await f.text());applyAgentUpdate(state,candidate);el.replaceChildren();for(const x of candidate.additions){const row=document.createElement('div');row.className='capture-entry';const title=document.createElement('strong');title.textContent=x.collection;const detail=document.createElement('pre');detail.className='note';detail.textContent=JSON.stringify(x.record,null,2);row.append(title,detail);el.append(row);}proposed=candidate;}catch(err){el.textContent=err.message;}});}
document.addEventListener('input',e=>{if(e.target.id==='quick-note')captureDraft=e.target.value;});
document.addEventListener('change',async e=>{if(e.target.id!=='capture-photo')return;const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2e6){toast('Choose a PNG, JPEG, or WebP under 2 MB.');return;}const epoch=sessionEpoch;const reader=new FileReader();reader.onload=()=>{if(epoch!==sessionEpoch)return;captureImage={name:f.name,data:reader.result};render();};reader.readAsDataURL(f);});
prepareDrive().catch(err=>{authError=err.message;if(mode==='locked')render();});
window.addEventListener('beforeunload',e=>{if(saving||saveFailed||captureDraft||captureImage){e.preventDefault();e.returnValue='';}});
render();

